spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/inventory-command
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  application:
    name: inventory-command-service


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: products-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

