spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-query
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  application:
    name: inventory-query-service
  kafka:
    bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
    consumer:
      group-id: products-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8082



